skip_tags: true
os: Visual Studio 2015
platform:
  - x64
  - x86
install:
  - git submodule update --init --recursive
  - ps: Install-Product node "" $env:platform # install deps under latest runtime (source-only deps will switch cleanly for tests)
  - npm install -g npm-add-script node-gyp
  - npmAddScript -f -k install -v "" # Disable the normal install script of this module
  - npm install # Install just dependencies
build_script:
  - .\node_modules\.bin\node-pre-gyp clean # make sure we start clean
  - node build_matrix.js "10.6.0 9.11.2 8.11.3 7.10.1 6.14.3 5.12.0 4.8.0 0.12.18" "3.0.0-beta.3 2.0.4 1.8.7 1.7.15 1.6.18 1.5.1 1.4.16 1.3.15"
artifacts:
  - path: 'build\stage\*\*.tar.gz'
test: OFF
before_deploy:
  - for /f "usebackq" %%v in (`node -e "console.log(JSON.parse(require ('fs').readFileSync('package.json')).name)"`) do set PKG_NAME=%%v # make the semver available for the deploy step
  - for /f "usebackq" %%v in (`node -e "console.log(JSON.parse(require ('fs').readFileSync('package.json')).version)"`) do set PKG_VER=%%v # make the semver available for the deploy step
deploy:
  provider: GitHub
  tag: $(PKG_VER)
  description: $(PKG_NAME) $(PKG_VER)
  auth_token:
    secure: gkLVM16ULpFG6pKrcHVJfkyrl+ZBUJFZUto6lBuTd7FkyUlOyHE6KilyIWzsseNc
  artifact: /.*/
  draft: false
  force_update: true
  prerelease: true
  on:
    branch: prebuilt
